import type { PositionDetailView } from "@/domains/front-api/viewModels";
import { operatorCode, operatorCopy } from "@/design-system/operatorVocabulary";
import { JourneyLink } from "./JourneyNavigation";
import { JourneyDisclosure, JourneySection } from "./JourneySurface";
import { positionDate, positionNumber, positionR } from "./positionPresentation";

export function PositionReading({ data }: { data: PositionDetailView }) {
  return <>
    <dl className="dj-metrics" aria-label="Synthèse de la position"><div><dt>Quantité publiée</dt><dd>{positionNumber(data.summary.quantity)}</dd></div><div><dt>Résultat publié</dt><dd>{positionR(data.summary.pnlR)}</dd></div><div><dt>Risque initial</dt><dd>{positionR(data.summary.riskR)}</dd></div><div><dt>Protection publiée</dt><dd>{operatorCode(data.summary.protectionStatus)}</dd></div></dl>
    <div className="dj-reading-grid"><JourneySection title="Prix et protection"><dl className="dj-terms"><div><dt>Entrée moyenne</dt><dd>{positionNumber(data.position.averagePrice)}</dd></div><div><dt>Stop</dt><dd>{positionNumber(data.position.stopPrice)}</dd></div><div><dt>Objectif</dt><dd>{positionNumber(data.position.targetPrice)}</dd></div></dl><dl className="dj-detail-lines"><div><dt>Ouverture</dt><dd>{positionDate(data.position.openedAt)}</dd></div><div><dt>Clôture</dt><dd>{positionDate(data.position.closedAt)}</dd></div><div><dt>État de protection</dt><dd>{operatorCode(data.position.protectionStatus)}</dd></div></dl><p className="dj-empty">Les niveaux affichés ne remplacent pas une preuve de protection effective chez le courtier. Consultez les ordres liés.</p></JourneySection>
      <JourneySection title="Ordres liés"><div className="dj-record-list">{data.orders.map((order) => <JourneyLink key={order.orderId} to={`/execution/orders/${encodeURIComponent(order.orderId)}`}><span><strong>{order.instrument} · {operatorCode(order.side)}</strong><small>{positionNumber(order.quantity)} contrat(s)</small></span><span>{operatorCode(order.state)}</span></JourneyLink>)}</div>{!data.orders.length ? <p className="dj-empty">Aucun ordre lié publié pour cette position.</p> : null}</JourneySection></div>
    <JourneySection title="Chronologie de la position">{data.lifecycle.length ? <ol className="dj-timeline">{data.lifecycle.map((event) => <li key={event.eventId}><time dateTime={event.at}>{positionDate(event.at)}</time><div><strong>{operatorCode(event.state)}</strong><p>{operatorCopy(event.detail)}</p></div></li>)}</ol> : <p className="dj-empty">Aucun événement de position publié.</p>}</JourneySection>
    <JourneyDisclosure title="Dossiers liés et références"><div className="dj-record-list">{data.relations.filter((item) => item.id && item.id !== "unavailable").map((item) => <JourneyLink key={`${item.label}-${item.id}`} to={item.route}>{operatorCode(item.label)}</JourneyLink>)}</div><dl className="dj-detail-lines"><div><dt>Position</dt><dd>{data.identity.positionId}</dd></div><div><dt>Signal</dt><dd>{data.identity.signalId}</dd></div><div><dt>Instance de stratégie</dt><dd>{data.identity.strategyInstanceId}</dd></div><div><dt>Corrélation</dt><dd>{data.identity.correlationId}</dd></div><div><dt>État source</dt><dd>{data.summary.state}</dd></div></dl></JourneyDisclosure>
    <p className="dj-empty">Consultation uniquement. Toute action d’exécution relève du parcours autorisé et audité du desk.</p>
  </>;
}
