export const DESK_COLLECTIONS = Object.freeze({
  tradingviewWebhookEvents: "tradingview_webhook_events",
  marketFeeds: "market_feeds",
  marketFeedCandles: "candles",
  marketFeedStudies: "studies",
  marketFeedEvents: "feed_events",
  studyCandles: "study_candles",
  liveStudyValues: "live_study_values",
  liveDataFeedStatus: "live_data_feed_status",

  deskCycles: "desk_cycles",
  deskCycleSnapshots: "desk_cycle_snapshots",
  deskAgentOutputs: "desk_agent_outputs",
  deskDebateResults: "desk_debate_results",
  deskRiskGateVerdicts: "desk_risk_gate_verdicts",
  deskReadyOrders: "desk_ready_orders",
  deskTradeOutcomes: "desk_trade_outcomes",
  deskSharedMemory: "desk_shared_memory",
  deskEngineStatus: "desk_engine_status",
  deskTelegramDeliveries: "desk_telegram_deliveries",
  deskRuntimeControl: "desk_runtime_control",

  dashboardCommands: "dashboard_commands",
  dashboardCommandEvents: "dashboard_command_events",
  systemWorkflowRequests: "system_workflow_requests",
  macroNewsState: "macro_news_state",
  macroCalendarEvents: "macro_calendar_events",

  decisionAudit: "decision_audit",
  simulationRuns: "simulation_runs",
  simulationSteps: "simulation_steps",
  paperDecisions: "paper_decisions",
  paperSetups: "paper_setups",
  paperPositions: "paper_positions",
  paperOutcomes: "paper_outcomes",
  paperReviews: "paper_reviews",
  workerMissions: "api_worker_missions",
  workerMonitors: "api_worker_monitors",
  hourlyRollups: "hourly_rollups",
  dashboardState: "dashboard_state",
  reviewRecords: "review_records",
  reviewBacklog: "review_backlog",

  deskPacks: "desk_packs",
  deskPackBuilds: "desk_pack_builds",
  deskDecisions: "desk_decisions",
  deskAnalyses: "desk_analyses",
  deskReports: "desk_reports",
  deskToolLogs: "desk_tool_logs",
  gptFeedbackEvents: "gpt_feedback_events",
  deskSetups: "desk_setups",
  deskSetupReplays: "desk_setup_replays",
  deskPositions: "desk_positions",
  deskDecisionJournal: "desk_decision_journal",
  deskContractRegistry: "desk_contract_registry",
  deskContracts: "desk_contracts",
  deskMasterAnalyses: "desk_master_analyses",
  deskActiveTheses: "desk_active_theses",
  deskHourlyMonitors: "desk_hourly_monitors",
  deskManualMonitors: "desk_manual_monitors",
  deskAlerts: "desk_alerts",
  deskContextTransmissions: "desk_context_transmissions",
  deskMonitorContextTransmissions: "desk_monitor_context_transmissions",
  deskMasterCutoffBundles: "desk_master_cutoff_bundles",
  deskMasterPrepJobs: "desk_master_prep_jobs",
  deskManualMonitorBundles: "desk_manual_monitor_bundles",
  deskMonitorPrepJobs: "desk_monitor_prep_jobs",
  deskJobs: "desk_jobs",
  deskFrontStates: "desk_front_states",
  deskFrontCurrentStates: "desk_front_current_states",
  deskFrontSnapshots: "desk_front_snapshots",
  deskFrontEvents: "desk_front_events",
  deskFrontProjectionErrors: "desk_front_projection_errors",
  deskBacktests: "desk_backtests",
  deskBacktestSteps: "desk_backtest_steps",
  deskSimulatedTrades: "desk_simulated_trades",
  deskBacktestResults: "desk_backtest_results",
  deskReplayRuns: "desk_replay_runs",
  deskReplaySteps: "desk_replay_steps",
  deskReplayBundles: "desk_replay_bundles",
  deskReplayMasterAnalyses: "desk_replay_master_analyses",
  deskReplayActiveTheses: "desk_replay_active_theses",
  deskReplaySetups: "desk_replay_setups",
  deskReplayMonitors: "desk_replay_monitors",
  deskReplayPositions: "desk_replay_positions",
  deskReplayTradeSimulations: "desk_replay_trade_simulations",
  deskReplayContextTransmissions: "desk_replay_context_transmissions",
  deskReplayTimeline: "desk_replay_timeline",
  deskReplayAuditLogs: "desk_replay_audit_logs",
  deskReplayIdempotency: "desk_replay_idempotency",
  deskAgentWorkItems: "desk_agent_work_items",
  deskAgentWorkEvents: "desk_agent_work_events",
  deskPromptRegistry: "desk_prompt_registry",
  deskStorageIncidents: "desk_storage_incidents",
  deskFeatureRuns: "desk_feature_runs",
  deskErrors: "desk_errors",
  deskLevelMaps: "desk_level_maps",
  deskTechnicalEvents: "desk_technical_events",
  deskLevelTestEvents: "desk_level_test_events",
  deskCrossAssetDeltas: "desk_cross_asset_deltas",
  deskConditionStatus: "desk_condition_status",
  deskSessionSnapshots: "desk_session_snapshots",
  deskRollingSnapshots: "desk_rolling_snapshots",
  deskDataQualityAudits: "desk_data_quality_audits",
  deskContractUpdateAudit: "desk_contract_update_audit",
  deskNotificationOutbox: "desk_notification_outbox",
  deskAuditLogs: "desk_audit_logs",
  deskStrategyTrades: "desk_strategy_trades",
  deskStrategyTradeExits: "desk_strategy_trade_exits",
  deskStrategyDailyPerformance: "desk_strategy_daily_performance",
  deskStrategyEquityCurve: "desk_strategy_equity_curve",
  deskStrategyStats: "desk_strategy_stats",
  deskStrategyDailyReviews: "desk_strategy_daily_reviews",

  replayJobs: "replay_jobs",
  replayJobEvents: "replay_job_events",
  replayComparisons: "replay_comparisons",
  replayReports: "replay_reports",

  brokerOrderIntents: "broker_order_intents",
  brokerOrderIntentEvents: "broker_order_intent_events",
  brokerRuntimeControl: "broker_runtime_control",
  brokerRuntimeEvents: "broker_runtime_events",

  strategyCatalog: "strategy_catalog",
  strategyConfigs: "strategy_configs",
  strategyRuntimeState: "strategy_runtime_state",
  strategySignals: "strategy_signals",
  strategyCandidates: "strategy_candidates",
  strategyMetricsDaily: "strategy_metrics_daily",
});

export const CDC_TARGET_COLLECTIONS = Object.freeze([
  DESK_COLLECTIONS.decisionAudit,
  DESK_COLLECTIONS.simulationRuns,
  DESK_COLLECTIONS.simulationSteps,
  DESK_COLLECTIONS.paperDecisions,
  DESK_COLLECTIONS.paperSetups,
  DESK_COLLECTIONS.paperPositions,
  DESK_COLLECTIONS.paperOutcomes,
  DESK_COLLECTIONS.paperReviews,
  DESK_COLLECTIONS.workerMissions,
  DESK_COLLECTIONS.workerMonitors,
  DESK_COLLECTIONS.hourlyRollups,
  DESK_COLLECTIONS.dashboardState,
  DESK_COLLECTIONS.reviewRecords,
  DESK_COLLECTIONS.reviewBacklog,
]);
