export interface ResearchLabSource { canonical: string; storage: string; direct_table_access: boolean }
export interface ResearchExperimentRow { research_experiment_id: string; experiment_key: string; name: string; objective: string; owner: string; status: string; comparison_metric: string; winner_simulation_run_id: string; created_at_utc: string; updated_at_utc: string; counts: { hypotheses: number; candidates: number; evaluation_reports: number; failed_reports: number; promotion_ready: number } }
export interface ResearchCandidateRow { research_candidate_id: string; research_experiment_id: string; research_hypothesis_id: string; candidate_key: string; status: string; source_type: string; strategy_definition_id: string; strategy_version_id: string; primary_change_summary: string; novelty_score: number | null; evaluation_score: number | null; last_evaluation_verdict: string; promotion_blocked: boolean; promotion_block_reason: string; created_at_utc: string; updated_at_utc: string; report_count: number; failed_report_count: number }
export interface ResearchHypothesisRow { research_hypothesis_id: string; research_experiment_id: string; statement: string; falsifiable_question: string; status: string; confidence_score: number | null; expected_outcome: string; invalidation_criteria: string; created_at_utc: string; updated_at_utc: string }
export interface ResearchEvaluationReportRow { research_evaluation_report_id: string; research_experiment_id: string; research_candidate_id: string; simulation_run_id: string; report_kind: string; verdict: string; score: number | null; metrics: Record<string, unknown>; criteria: Record<string, unknown>; artifact_refs: string[]; created_at_utc: string }
export interface ResearchLabOverview { contract: "DeskResearchLabOverviewV1"; schemaVersion: "research_lab_front_v1"; generated_at_utc: string; source: ResearchLabSource; summary: { experiments: number; active_experiments: number; hypotheses: number; candidates: number; promotion_ready: number; blocked_candidates: number; evaluation_reports: number; failed_reports: number }; experiments: ResearchExperimentRow[]; candidates: ResearchCandidateRow[]; evaluation_reports: ResearchEvaluationReportRow[]; knowledge_graph: { summary: Record<string, number | string | null>; graph_hash?: string | null } }
export interface ResearchExperimentDetail { contract: "DeskResearchExperimentDetailV1"; schemaVersion: "research_lab_front_v1"; generated_at_utc: string; source: ResearchLabSource; experiment: ResearchExperimentRow; hypotheses: ResearchHypothesisRow[]; candidates: ResearchCandidateRow[]; evaluation_reports: ResearchEvaluationReportRow[]; knowledge_graph: { summary: Record<string, number | string | null> } }
export interface ResearchCandidateDetail { contract: "DeskResearchCandidateDetailV1"; schemaVersion: "research_lab_front_v1"; generated_at_utc: string; source: ResearchLabSource; candidate: ResearchCandidateRow; experiment: ResearchExperimentRow | null; hypothesis: ResearchHypothesisRow | null; evaluation_reports: ResearchEvaluationReportRow[] }
export interface ResearchListEnvelope<T> { contract: string; schemaVersion: "research_lab_front_v1"; generated_at_utc: string; count: number; items: T[] }
