import { Link, useParams } from "react-router-dom";
import { Card, KpiCard, StatusBadge } from "@/design-system/primitives";
import { MetricBox, OperatorPageHeader } from "@/design-system/workspace";
import { ViewTruthBanner } from "@/design-system/states";
import { useFrontView } from "@/domains/front-api/repositories";

export function IncidentDetailPage() {
  const { incidentId } = useParams();
  const query = useFrontView("incident-detail", { incidentId });
  if (query.isLoading) return <div className="operator-page"><Card state="loading" density="compact"><p>Chargement de l’incident…</p></Card></div>;
  if (query.isError || !query.data) return <div className="operator-page"><Card title="Incident indisponible" eyebrow="ERREUR CONTRAT" tone="danger" density="compact"><p>{query.error instanceof Error ? query.error.message : "Projection absente"}</p><Link to="/operations/incidents">Retour aux incidents</Link></Card></div>;
  const { data, meta } = query.data;
  return <div className="operator-page incident-detail-page"><ViewTruthBanner meta={meta} /><OperatorPageHeader title={data.incident.title} description={`${data.incident.incidentId} · ${data.incident.domain} · projection ${meta.latencyMs} ms.`} actions={<><Link to="/operations/incidents">Retour incidents</Link><Link to="/operations/events">Audit global</Link></>} />
    <section className="operator-kpi-strip" aria-label="Indicateurs incident"><KpiCard label="SÉVÉRITÉ" value={data.summary.severity} delta={data.incident.domain} tone={data.summary.severity === "CRITICAL" || data.summary.severity === "HIGH" ? "danger" : "warning"} /><KpiCard label="ÉTAT" value={data.summary.status} delta={data.incident.updatedAt} tone={data.summary.status === "RESOLVED" ? "success" : "warning"} /><KpiCard label="RETRIES" value={`${data.summary.retryCount}`} delta={`${data.retries.length} publiés`} /><KpiCard label="GATE" value={data.summary.operatorGate} delta="autorité opérateur" tone="info" /><KpiCard label="IMPACT" value={`${data.incident.impactR >= 0 ? "+" : ""}${data.incident.impactR.toFixed(2)} R`} delta={data.incident.impactSummary} tone={data.incident.impactR < 0 ? "danger" : "neutral"} /><KpiCard label="CORRÉLATION" value={data.incident.correlationId} delta="trace end-to-end" /></section>
    <section className="operator-grid operator-grid--top" aria-label="Cause, payload et relations"><Card title="Diagnostic" density="compact"><p>{data.incident.detail}</p><div className="reconciliation-grid"><MetricBox label="Recommandation" value={data.incident.machineRecommendation} /><MetricBox label="Ouvert" value={stamp(data.incident.openedAt)} /><MetricBox label="Mis à jour" value={stamp(data.incident.updatedAt)} /><MetricBox label="Provider" value={data.incident.providerId ?? "Indisponible"} /></div></Card><Card title="Payload & meta" density="compact"><div className="reconciliation-grid">{data.payloadPreview.map((item) => <MetricBox key={item.key} label={item.key} value={item.value} />)}{data.meta.map((item) => <MetricBox key={item.label} label={item.label} value={item.value} />)}</div></Card><Card title="Relations" density="compact"><div className="zoom-link-list">{data.relations.filter((item) => item.id !== "unavailable").map((item) => <Link key={`${item.label}-${item.id}`} to={item.route}><strong>{item.label}</strong><small>{item.id}</small></Link>)}</div></Card></section>
    <section className="operator-grid operator-grid--bottom" aria-label="Chronologie, réconciliation et post-mortem"><Card title="Chronologie" density="compact">{data.chronology.length ? <ol className="timeline">{data.chronology.map((step) => <li className="timeline__item" key={step.stepId}><span>{stamp(step.at)}</span><strong>{step.title}</strong><small>{step.detail}</small></li>)}</ol> : <p className="empty-state">Chronologie détaillée non publiée.</p>}</Card><Card title="Réconciliation" density="compact">{data.reconciliationResults.length ? data.reconciliationResults.map((item) => <article className="detail-list-row" key={item.resultId}><div><strong>{item.label}</strong><small>{item.expected} → {item.actual}</small></div><StatusBadge tone={item.status === "MATCH" || item.status === "REPAIRED" ? "success" : "warning"}>{item.status}</StatusBadge></article>) : <p className="empty-state">Résultats de réconciliation non publiés.</p>}</Card><Card title="Post-mortem" density="compact"><div className="reconciliation-grid"><MetricBox label="Cause racine" value={data.postMortem.rootCause} /><MetricBox label="Confinement" value={data.postMortem.containment} /><MetricBox label="Correction" value={data.postMortem.permanentFix} /><MetricBox label="Responsable" value={data.postMortem.ownerRole} /></div></Card></section>
  </div>;
}
function stamp(value: string) { const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? "Indisponible" : new Intl.DateTimeFormat("fr-FR", { dateStyle: "short", timeStyle: "medium" }).format(parsed); }
